name: Deploy to Cloud Run

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Configure Docker auth
        run: gcloud auth configure-docker gcr.io --quiet

      - name: Build and push image
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT }}/autovalue-insight:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE_URL=$IMAGE" >> $GITHUB_ENV

      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: infra/terraform
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT }}
          TF_VAR_image_url: ${{ env.IMAGE_URL }}
        run: terraform apply -auto-approve
